https://github.com/jugs-org/webdav/actions/workflows/maven.yml[image:https://github.com/jugs-org/webdav/actions/workflows/maven.yml/badge.svg[Build Status]]

= Releases

This document contains some information about the CI build, release notes and deployment.
Other infos are present in the top link:../../README.md[README].



== CI Build

No CI build is configured for the moment.



== Release Notes

* see link:../../CHANGELOG.md[CHANGELOG]



== Deployment

This is a little checklist for the next release:

.Ordered
. create a release branch and change to it
. remove -SNAPSHOT in pom.xml (`mvn versions:set` followed by `mvn versions:commit`)
. build all artifacts and deploy it:
  `mvn -Psign clean install source:jar javadoc:jar deploy gpg:sign -Dgpg.passphrase=xxxxxxxxx`
. after successful deployment go to https://central.sonatype.com/publishing/deployments and _Publish_ it
. update link:../../CHANGELOG.md[CHANGELOG]
. checkin the pom.xml (if not already done), label the sources, e.g. with "webdav-3.3.1" and push it (`git push --tags`)
. draft a new release under https://github.com/jugs-org/webdav/releases[Releases] using the new tag
. merge the release branch to main and develop branch
. change to develop branch and start next SNAPSHOT
. after a few days: check webdav with http://search.maven.org/#search%7Cga%7C1%7Cwebdav[search.maven.org]
