= Releases

This document contains some information about the CI build, release notes and deployment.
Other infos are present in the top link:../../README.md[README].



== CI Build

No CI build is configured for the moment.



== Release Notes

* see link:../../CHANGELOG.md[CHANGELOG]



== Deployment

This is a little checklist for the next release:

.Ordered
. create a release branch and change to it
. remove -SNAPSHOT in pom.xml (`mvn versions:set` followed by `mvn versions:commit`)
. build all artifacts:
  `mvn -B clean install source:jar javadoc:jar gpg:sign -Dgpg.passphrase=xx`
. use the script `src/script/deploy.sh` to upload bundles to https://s01.oss.sonatype.org/
  (but don't forget to update the VERSION variable inside this script).
. after upload to the staging repository https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-8.ReleaseIt[release it]:
  select "Staging Repositories" on https://s01.oss.sonatype.org/[s01.oss.sonatype.org], press "Refresh" and then "Close" and "Release".
. update link:../../CHANGELOG.md[CHANGELOG]
. checkin the pom.xml (if not already done), label the sources, e.g. with "webdav-2.0" and push it (`git push --tags`)
. merge the release branch to master and develop branch
. change to develop branch and start next SNAPSHOT
. after a few days: check webdav with http://search.maven.org/#search%7Cga%7C1%7Cwebdav[search.maven.org]
